PortfolyoWebSiteUI/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace PortfolyoWebSiteUI.Controllers
{
    public class ServiceController : Controller
    {
        private ServiceManager sm = new ServiceManager(new EfServiceDal());

        private ServiceValidator sv = new ServiceValidator();

        private ValidationResult vr;
        // GET: Service
        public ActionResult Index()
        {
            ViewBag.add = TempData["add"];
            ViewBag.edit = TempData["edit"];
            var result = sm.GetList();
            return View(result);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Service entity)
        {
            vr = sv.Validate(entity);
            if (vr.IsValid)
            {
                TempData["add"] = "true";
                string fileName = Path.GetFileName(Request.Files[0]?.FileName);
                string extension = Path.GetExtension(Request.Files[0]?.FileName);
                string path = "/Image/" + fileName + extension;
                Request.Files[0].SaveAs(Server.MapPath(path));
                entity.Img = path;
                sm.Add(entity);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in vr.Errors)
                {
                    ModelState.AddModelError(error.PropertyName,error.ErrorMessage);
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var result = sm.GetById(id);
            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(Service entity)
        {
            vr = sv.Validate(entity);
            if (vr.IsValid)
            {
                TempData["edit"] = "true";
                string fileName = Path.GetFileName(Request.Files[0]?.FileName);
                string extension = Path.GetExtension(Request.Files[0]?.FileName);
                string path = "/Image/" + fileName + extension;
                Request.Files[0]?.SaveAs(Server.MapPath(path));
                entity.Img = path;
                sm.Update(entity);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in vr.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            var result = sm.GetById(id);
            sm.Delete(result);
            return RedirectToAction("Index");
        }
    }
}

PortfolyoWebSiteUI/Views/Service/Add.cshtml
@model EntityLayer.Concrete.Service
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin: 0px 10% 20px 10%" class="form-group">

    @using (Html.BeginForm("Add", "Service", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {<form>
         <div class="form-row">
             <div class="form-group col-md-6">
                 @Html.Label("Hizmet Adı", new { @class = "text-bold" })
                 @Html.TextBoxFor(x => x.Name, new { @class = "form-control " })
                 @Html.ValidationMessageFor(x => x.Name)
             </div>
             <div class="form-group col-md-6">
                 @Html.Label("Hizmet İkon", new { @class = "text-bold" })
                 <input type="file" name="Img" class="form-control" />
                 @Html.ValidationMessageFor(x => x.Img)
             </div>
         </div>
         <div class="form-row">
             <div class="form-group col-md-12">
                 @Html.Label("Hizmet Hakkında", new { @class = "text-bold" })
                 @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                 @Html.ValidationMessageFor(x => x.Description)
             </div>
         </div>

         <button class="btn btn-outline-info">Kaydet</button>
     </form>
    }


</div>

PortfolyoWebSiteUI/Views/Service/Edit.cshtml
@model EntityLayer.Concrete.Service
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin: 0px 10% 20px 10%" class="form-group">

    @using (Html.BeginForm("Edit", "Service", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {<form>
            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.Label("Hizmet Adı", new { @class = "text-bold" })
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control " })
                    @Html.ValidationMessageFor(x => x.Name)
                </div>
                <div class="form-group col-md-6">
                    @Html.Label("Hizmet İkon", new { @class = "text-bold" })
                    <input type="file" name="Img" class="form-control" />
                    @Html.ValidationMessageFor(x => x.Img)
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    @Html.Label("Hizmet Hakkında", new { @class = "text-bold" })
                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Description)
                </div>
            </div>

            <button class="btn btn-outline-info">Kaydet</button>
        </form>
    }


</div>

PortfolyoWebSiteUI/Views/Service/Index.cshtml
@using EntityLayer.Concrete
@model List<Service>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">
    <div class="text-right" style="margin-bottom: 8px">
        <a class="btn btn-outline-success" href="/Service/Add/">Yeni Hizmet Ekle</a>
    </div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Hizmetler</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 15%">
                            Hizmet İsmi
                        </th>
                        <th style="width: 20%">
                            Hizmet Görsel
                        </th>
                        <th style="width: 30%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <a>
                                    @item.Name
                                </a>
                            </td>

                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="img-size-50 " src="@item.Img">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-outline-warning " href="/Service/Edit/@item.Id">
                                    <i class="fas fa-pencil-alt">
                                    </i>

                                </a>
                                <a href="@Url.Action("Delete", "Service", new { id = @item.Id })" id="delet" class="btn btn-outline-danger"><i class="far fa-trash-alt"></i> </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<script type="text/javascript">
    // sweetalert delete
    $('.btn-outline-danger').on('click', function (e) {
        e.preventDefault();
        var url = $(this).attr('href');
        Swal.fire({
            title: 'Hizmet silmek istediğinizden emin misiniz?',
            text: "Bu işlem geri alınamaz!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Evet, sil!',
            cancelButtonText: 'Vazgeç'
        }).then((result) => {
            if (result.value) {
                // Eğer kullanıcı 'Evet, sil!' butonuna tıklar ise burada ürünü silmek için gerekli kodları yazın
                $.ajax({
                    url: url,
                    type: 'POST',
                    success: function (result) {
                        if (result) {
                            Swal.fire(
                                'Silindi!',
                                'Hizmet başarıyla silindi.',
                                'success'
                            ).then(() => {
                                location.reload();
                            });
                        }
                    }
                });
            }
        });
    });

</script>



<script>
// sweetalert add
    var alertAdd = "@((string) ViewBag.add)";
    if (alertAdd != null && alertAdd != "") {
        swal.fire("", "Yeni hizmet başarılı bir şekilde eklendi.", "success");
    }

</script>

<script>
// sweetalert edit
    var alertEdit= "@((string) ViewBag.edit)";
    if (alertEdit != null && alertEdit != "") {
        swal.fire("", "Hizmet başarılı bir şekilde güncellendi.", "success");
    }
</script>