PortfolyoWebSiteUI/Controllers/SocialMediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace PortfolyoWebSiteUI.Controllers
{
    public class SocialMediaController : Controller
    {
        private SocialMediaManager smm = new SocialMediaManager(new EfSocialMediaDal());
        private SocialMediaValidator smv = new SocialMediaValidator();
        private ValidationResult vr;
        public ActionResult Index()
        {
            ViewBag.edit = TempData["edit"] as string;
           var result = smm.GetList();
            return View(result);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var result = smm.GetById(id);
            return View(result);
        }

        [HttpPost]
        public ActionResult Edit(SocialMedia entity)
        {
            vr = smv.Validate(entity);
            if (vr.IsValid)
            {
                TempData["edit"] = "true";
                entity.Status = true;
                smm.Update(entity);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in vr.Errors)
                {
                    ModelState.AddModelError(error.PropertyName,error.ErrorMessage);
                }
            }

            return View();
        }


        public ActionResult Status(int id)
        {
            var result = smm.GetById(id);
            smm.Update(result);
            return RedirectToAction("Index");
        }


    }
}

PortfolyoWebSiteUI/Views/SocialMedia/Edit.cshtml
@model EntityLayer.Concrete.SocialMedia
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="margin: 0px 10% 20px 10%" class="form-group">

    @using (Html.BeginForm("Edit", "SocialMedia", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {<form>
            <div class="form-row">
                <div class="form-group col-md-12">
                    @Html.HiddenFor(x => x.Name, new { @class = "form-control " })
                    @Html.HiddenFor(x => x.Icon, new { @class = "form-control " })
                    @Html.HiddenFor(x => x.Status, new { @class = "form-control " })
                    @Html.Label("Sosyal Mesya Adresi", new { @class = "text-bold" })
                    @Html.TextBoxFor(x => x.Link, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Link)
                </div>
            </div>
         <button class="btn btn-outline-info">Kaydet</button>
        </form>
    }


</div>

PortfolyoWebSiteUI/Views/SocialMedia/Index.cshtml
@using EntityLayer.Concrete
@model List<SocialMedia>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    string color = "";
    string icon = "";
}

<section class="content">
    <div class="text-right" style="margin-bottom: 8px">
    </div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Sosyal Medya Hesaplarım</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 15%">
                            İcon
                        </th>
                        <th style="width: 15%">
                            Sosyal Medya
                        </th>
                        <th style="width: 10%">
                            Kullanıcı Adı
                        </th>
                        <th>
                            Durum
                        </th>
                        <th style="width: 10%">
                            İşlem
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (@item.Status == true)
                        {
                            color = "btn-outline-success";
                            icon = "fa-pause";

                        }
                        else
                        {
                            color = "btn-outline-danger";
                            icon = "fa-play";

                        }
                        <tr>
                            <td>
                                <a>
                                    <li class="list-inline-item">
                                        <img alt="@item.Name" class="img-size-50" src="@item.Icon">
                                    </li>
                                </a>
                            </td>
                            <td>
                                <a>
                                    @item.Name
                                </a>
                            </td>

                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <a>@item.Link</a>
                                    </li>
                                </ul>
                            </td>
                            <td>

                                <a id="status" class="btn @color" href="/SocialMedia/Status/@item.Id">
                                    <i class="fas @icon">
                                    </i>
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-outline-warning " href="/SocialMedia/Edit/@item.Id">
                                    <i class="fas fa-pencil-alt">
                                    </i>

                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

<script type="text/javascript">
    // sweetalert status devre dışı
    $('.btn-outline-success').on('click', function (e) {
        e.preventDefault();
        var url = $(this).attr('href');
        Swal.fire({
            title: 'Hesabı devre dışı bırakmak istediğinizden emin misiniz?',
            text: "",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Evet',
            cancelButtonText: 'Vazgeç'
        }).then((result) => {
            if (result.value) {
                // Eğer kullanıcı 'Evet, sil!' butonuna tıklar ise burada ürünü silmek için gerekli kodları yazın
                $.ajax({
                    url: url,
                    type: 'POST',
                    success: function (result) {
                        if (result) {
                            Swal.fire(
                                'Devre dışı!',
                                'Hesab devre dışı bırakıldı.',
                                'success'
                            ).then(() => {
                                location.reload();
                            });
                        }
                    }
                });
            }
        });
    });

</script>

<script type="text/javascript">
    // sweetalert status aktif edildi
    $('.btn-outline-danger').on('click', function (e) {
        e.preventDefault();
        var url = $(this).attr('href');
        Swal.fire({
            title: 'Hesabı aktif ekmek istediğinizden emin misiniz?',
            text: "",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Evet',
            cancelButtonText: 'Vazgeç'
        }).then((result) => {
            if (result.value) {
                // Eğer kullanıcı 'Evet, sil!' butonuna tıklar ise burada ürünü silmek için gerekli kodları yazın
                $.ajax({
                    url: url,
                    type: 'POST',
                    success: function (result) {
                        if (result) {
                            Swal.fire(
                                'Aktif edildi!',
                                'Hesab aktif edildi.',
                                'success'
                            ).then(() => {
                                location.reload();
                            });
                        }
                    }
                });
            }
        });
    });

</script>


<script>
// sweetalert edit
    var alertEdit= "@((string) ViewBag.edit)";
    if (alertEdit != null && alertEdit != "") {
        swal.fire("", "Hesap başarılı bir şekilde güncellendi.", "success");
    }
</script>